Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernada nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : kauan alves
// Data atual  : 17/12/2024

var
cont, soma: inteiro
inicio
soma <- 0
para cont de 1 ate 100 faca
soma <- soma + cont
fimpara
escreval("A soma dos cem primeiros números é: ", soma)
fimalgoritmo