Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Kauan Alves
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 10
para cont <- 10 ate 1 passo -1 faca
escreval (cont)
fimpara

Fimalgoritmo