Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Kauan Alves Moraes
// Data atual  : 04/12/2024
Var
valor, antecessor: inteiro

Inicio
escreva("Digite um valor: ")
 leia(valor)
  antecessor <- valor - 1
  escreva("O antecessor de ", valor, " é ", antecessor)
  
Fimalgoritmo