Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Kauan Alves Moraes
// Data atual  : 04/12/2024
Var
valor, sucessor: inteiro

Inicio
escreva("Digite um valor: ")
 leia(valor)
  sucessor <- valor + 1
  escreva("O sucessor de ", valor, " é ", sucessor)

Fimalgoritmo