Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : atividade enquanto B
// Autor(a)    :Kauan Alves
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
resultado: inteiro


Inicio



enquanto resultado < 10 faca

resultado <- resultado + 1



escreval (resultado)

fimenquanto









Fimalgoritmo