Algoritmo "Tabuada 8 código PARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Exemplo PARA
// Autor(a)    : Lara dos Santos Dourado
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
numero, total: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numero <- 1 ate 10 faca
    total <- 12 * numero
    escreval("12 x ", numero, " = ", total)
fimpara



Fimalgoritmo